### ISSUE TITLE
CSS revamp

### ISSUE THREAD

**Issue by maxdevjs** [maxdevjs/learn-dio-covid-19#1]
[global-styles.js](https://github.com/maxdevjs/learn-dio-covid-19/blob/master/covid-19/src/commons/styles/global-styles.js) deserves some <3

**Comment by highflyer910** [comment]
I'd love to work on it 😊

**Comment by maxdevjs** [comment]
Welcome, do a great work :tada:

Note: it refers exclusively to the linked file.

**Comment by maxdevjs** [comment]
Tag is on.
